site_name: Blrf ORM documentation
site_dir: docs

repo_url: https://github.com/dmarkic/orm
repo_name: blrf/orm

theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    #- navigation.tabs
    - navigation.sections
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annoation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: range
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: lime

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Model: model.md
  - Attributes: attributes.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dmarkic/orm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MarkicDejan

copyright: |
  &copy; 2024 <a href="https://github.com/dmarkic" target="_blank" rel="noopener">Dejan Markič</a>
